kind: pipeline
name: my-super-pipeline-ci

steps:
- name: template
  image: lowess/preact-cli
  commands:
  - preact create ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}#${DRONE_COMMIT} test-ci

- name: dependencies
  image: lowess/preact-cli
  commands:
  - cd test-ci
  - npm install

- name: build
  image: lowess/preact-cli
  commands:
  - cd test-ci
  - npm run build

- name: notify  
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: drone-ci
    template: >
      {{#success build.status}}
        Matthew build {{build.number}} succeeded. Good job.
      {{else}}
        Matthew build {{build.number}} failed. Fix me please.
      {{/success}}

# - name: delivery  
#   image: plugins/gh-pages
#   settings:
#     username: amco3008
#     password: a8c8de86093840c346fbf00f4af7aaa1b55219ae
#     pages_directory: test-ci/dist/

# - name: deploy  
#   image: plugins/gh-pages
#   settings:
#     username: amco3008
#     password: a8c8de86093840c346fbf00f4af7aaa1b55219ae
#     pages_directory: test-ci/dist/