kind: pipeline
name: my-super-pipeline-ci

steps:
- name: template
  image: lowess/preact-cli
  commands:
  - preact create ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}#${DRONE_COMMIT} test-ci

- name: dependencies
  image: lowess/preact-cli
  commands:
  - cd test-ci
  - npm install

- name: build
  image: lowess/preact-cli
  commands:
  - cd test-ci
  - npm run build

- name: deploy  
  image: plugins/gh-pages
  settings:
    pages_directory: test-ci/dist/
    upstream_name: origin

# - name: deploy
#   image: lowess/preact-cli
#   commands:
#   - cd /drone/src/test-ci
#   - npm run build